### ISSUE TITLE
Scope / content / strategy missing

### ISSUE THREAD

**Issue by khufkens** [geco-bern/grsofun#1]
@stineb

I see:
- no content / project description in README.md
- no co-authors listed in DESCRIPTION or README.md
- no strategy / timeline (in projects or documented with issues or in README.md)

Please document all the above or move back to personal account. geco-bern is for mature projects, personal accounts should be used for initial development - unless the above conditions are met.

**Comment by stineb** [comment]
I'll transfer it to stineb (personal acccount) - which I initially intended but accidentally created it in geco-bern.
